### ISSUE TITLE
Ported to the Rosé Pine organisation

### ISSUE THREAD

**Issue by mvllow** [aleck07/youtube#5]
Hey there, thanks for creating this theme! I copied it over to the Rosé Pine org to include it in our [userstyles](https://github.com/rose-pine/userstyles) repository. Happy to make you a collaborator if you'd like to continue work over there!

**If you'd rather not have a version inside the Rosé Pine org please let me know here or via email and we'll remove it.**

**Comment by aleck07** [comment]
Sorry for such a late reply, I haven't been on my personal GitHub account in a while because I'm always on my college account, but I would be happy to be a collaborator in the Rose Pine org so I can update the repo in the org. Thank you!

**Comment by mvllow** [comment]
No worries at all, I invited you to the userstyles repo :)
